 # Deployment  Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Big Rock Candy Mountains
subtitle: 人生那么长，可我就在你眼前——巨石糖果山x³
description: Big Rock Candy Mountains, 随笔, 生活, 美文, 技术, 摄影, 思想
keywords: Big Rock Candy Mountains, 巨石糖果山, 黑凤梨，博客，生活，记录，编程，美文
author: 巨石糖果山x³
language: zh-Hans
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.blog.heifengni.com/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
#archive_dir: archives
category_dir: categories
#code_dir: downloads/code
#i18n_dir: :lang
#skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
# 是否打开预览草稿
render_drafts: false #线上开启草稿预览
post_asset_folder: false
relative_link: false
future: false

# 代码高亮
highlight:
  enable: false
  line_number: false
  auto_detect: false
  tab_replace:

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path:
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
## my_themes list [yilia ,landscape,next]
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  #repository: https://github.com/jushitangguoshan/jushitangguoshan.github.io.git
  #branch: master
  repo:
    github: git@github.com:jushitangguoshan/jushitangguoshan.github.io.git,master
#    coding: git@git.coding.net:jushitangguoshan/blogs_hexo.git,master
  branch: gitcafe-pages
  message: update
  # Live2D
 ## https://github.com/EYHN/hexo-helper-live2d
live2d:
  enable: true
  scriptFrom: jsdelivr # 默认
  pluginRootPath: live2dw/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
   # scriptFrom: jsdelivr # jsdelivr CDN
   # scriptFrom: unpkg # unpkg CDN
   # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js # 你的自定义 url
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: shizuku # live2d-widget-model-hijiki  npm-module package name [tororo wanko hijiki]
    # use: hijiki # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/hijiki # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-hijiki@1.0.5/assets/hijiki.model.json # 你的自定义 url
    scale: 1
    hHeadPos: 0
    vHeadPos: 0.618
  display: # 模型位置，根据不同的模型自行调整
    position: left
    width: 150
    height: 300
    hOffset:
    vOffset:
  mobile:
    show: true
    scale: 0.6
  react:
      opacityDefault: 0.2
      opacityOnHover:

# qiniu-storage
qiniu:
  offline: false
  sync: true
  bucket: qiniu_storage
  # secret_file: sec/qn.json or C:
  access_key: _a84dBRWph1OoEYiGnFO7ZTJaFeHrf5ssjrCB4dT
  secret_key: LJ-oWZiEWFoixk09cQJUWu2CGRv-rtOwfkkYsUHk
  dirPrefix: qiniu_images
  urlPrefix: http://qiniu.storage.heifengni.com/qiniu_images
  up_host: http://upload.qiniu.com
  local_dir: qiniu_storage
  update_exist: true
  image:
    folder: images
    extend:
  js:
    folder: js
  css:
    folder: css

# Extensions 插件【Feed Atom、sitemap】
Plugins:
  - hexo-generator-feed
  - hexo-generator-sitemap
#Feed Atom
feed:
  type: atom
  path: atom.xml
  limit: 20
#sitemap
# SEO
sitemap:
  path: sitemap.xml
baidusitemap:
  path: baidusitemap.xml

 # Blogrolls
links_title: 推荐阅读
 #links_layout: block
links_layout: inline
links:
  聂哥的博客: http://aipanshi.com


# 百度分享功能

#skip_rende: static/**
# 自由敲回车换行
marked:
  gfm: true
  pedantic: false
  sanitize: false
  tables: true
  breaks: false
  smartLists: true
  smartypants: true
  modifyAnchors: ''
  autolink: true
# 搜索
search:
  path: search.xml
  field: post
  format: html
  limit: 10000

